title: Soil Analyst
description: Soil analyst is a simple application created to help african farmers perform test of their soils properties and also measure the area of their land.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
